import { QuranAyahViewModel } from "./quranTypes";

const SURAH_DATA: Record<number, QuranAyahViewModel[]> = {
  112: [
    {
      id: 112001,
      surahNumber: 112,
      ayahNumber: 1,
      surahNameAr: "الإخلاص",
      surahNameEn: "Al-Ikhlas",
      textTashkeel: "قُلْ هُوَ ٱللَّهُ أَحَدٌ",
      page: 604,
      juz: 30,
    },
    {
      id: 112002,
      surahNumber: 112,
      ayahNumber: 2,
      surahNameAr: "الإخلاص",
      surahNameEn: "Al-Ikhlas",
      textTashkeel: "ٱللَّهُ ٱلصَّمَدُ",
      page: 604,
      juz: 30,
    },
    {
      id: 112003,
      surahNumber: 112,
      ayahNumber: 3,
      surahNameAr: "الإخلاص",
      surahNameEn: "Al-Ikhlas",
      textTashkeel: "لَمْ يَلِدْ وَلَمْ يُولَدْ",
      page: 604,
      juz: 30,
    },
    {
      id: 112004,
      surahNumber: 112,
      ayahNumber: 4,
      surahNameAr: "الإخلاص",
      surahNameEn: "Al-Ikhlas",
      textTashkeel: "وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ",
      page: 604,
      juz: 30,
    },
  ],
  113: [
    {
      id: 113001,
      surahNumber: 113,
      ayahNumber: 1,
      surahNameAr: "الفلق",
      surahNameEn: "Al-Falaq",
      textTashkeel: "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ",
      page: 604,
      juz: 30,
    },
    {
      id: 113002,
      surahNumber: 113,
      ayahNumber: 2,
      surahNameAr: "الفلق",
      surahNameEn: "Al-Falaq",
      textTashkeel: "مِن شَرِّ مَا خَلَقَ",
      page: 604,
      juz: 30,
    },
    {
      id: 113003,
      surahNumber: 113,
      ayahNumber: 3,
      surahNameAr: "الفلق",
      surahNameEn: "Al-Falaq",
      textTashkeel: "وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ",
      page: 604,
      juz: 30,
    },
    {
      id: 113004,
      surahNumber: 113,
      ayahNumber: 4,
      surahNameAr: "الفلق",
      surahNameEn: "Al-Falaq",
      textTashkeel: "وَمِن شَرِّ ٱلنَّفَّـٰثَـٰتِ فِى ٱلْعُقَدِ",
      page: 604,
      juz: 30,
    },
    {
      id: 113005,
      surahNumber: 113,
      ayahNumber: 5,
      surahNameAr: "الفلق",
      surahNameEn: "Al-Falaq",
      textTashkeel: "وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
      page: 604,
      juz: 30,
    },
  ],
  114: [
    {
      id: 114001,
      surahNumber: 114,
      ayahNumber: 1,
      surahNameAr: "الناس",
      surahNameEn: "An-Nas",
      textTashkeel: "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ",
      page: 604,
      juz: 30,
    },
    {
      id: 114002,
      surahNumber: 114,
      ayahNumber: 2,
      surahNameAr: "الناس",
      surahNameEn: "An-Nas",
      textTashkeel: "مَلِكِ ٱلنَّاسِ",
      page: 604,
      juz: 30,
    },
    {
      id: 114003,
      surahNumber: 114,
      ayahNumber: 3,
      surahNameAr: "الناس",
      surahNameEn: "An-Nas",
      textTashkeel: "إِلَـٰهِ ٱلنَّاسِ",
      page: 604,
      juz: 30,
    },
    {
      id: 114004,
      surahNumber: 114,
      ayahNumber: 4,
      surahNameAr: "الناس",
      surahNameEn: "An-Nas",
      textTashkeel: "مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ",
      page: 604,
      juz: 30,
    },
    {
      id: 114005,
      surahNumber: 114,
      ayahNumber: 5,
      surahNameAr: "الناس",
      surahNameEn: "An-Nas",
      textTashkeel: "ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ",
      page: 604,
      juz: 30,
    },
    {
      id: 114006,
      surahNumber: 114,
      ayahNumber: 6,
      surahNameAr: "الناس",
      surahNameEn: "An-Nas",
      textTashkeel: "مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ",
      page: 604,
      juz: 30,
    },
  ],
};

export function getSurahAyat(surah: number): QuranAyahViewModel[] {
  const rows = SURAH_DATA[surah] ?? [];
  return rows.map((row) => ({ ...row }));
}
